.init_template:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  extends: .aws_base
  stage: init
  interruptible: true
  script:
    - cd $ENV
    - terraform init
  artifacts:
    paths:
      - $ENV/.terraform
      - $ENV/.terraform.lock.hcl
    expire_in: 1 hour
  # Add these rules to your existing .gitlab-ci.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - "${ENV}/**/*"
        - "modules/**/*"
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - "${ENV}/**/*"
        - "modules/**/*"

dev:init:
  extends: .init_template
  needs:
    - job: dev:aws:assume_role
      artifacts: true
  variables:
    ENV: dev
  
staging:init:
  extends: .init_template
  needs:
    - job: staging:aws:assume_role
      artifacts: true
  variables:
    ENV: staging

prod:init:
  extends: .init_template
  needs:
    - job: prod:aws:assume_role
      artifacts: true
  variables:
    ENV: prod
